PROJECT:=ComputerGraphics

include makefile-latex/latex-std-dependence.mk
DEPS_MAIN_TEX:=${STYS_MINIMUS} ${CLSS_NOTEBOOK_NEON}
DEPS_FIGS_TEX:=${STYS_MINIMUS} ${CLSS_STANDALONE_SILICON}

include makefile-latex/makefile-latex.mk

${BUILD_DIR}/Chapter07A_06.fig.pdf: ${BUILD_DIR}/Chapter07A_01.fig.pdf ${BUILD_DIR}/Chapter07A_02.fig.pdf ${BUILD_DIR}/Chapter07A_03.fig.pdf ${BUILD_DIR}/Chapter07A_04.fig.pdf ${BUILD_DIR}/Chapter07A_05.fig.pdf